# App
quarkus.application.name=reservas-service
quarkus.http.port=8080

# Datasource REACTIVO
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USERNAME:reservas_user}
quarkus.datasource.password=${DB_PASSWORD:reservas_pass}
quarkus.datasource.reactive.url=mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:reservas_db}?charset=utf8mb4&collation=utf8mb4_unicode_ci

# Datasource JDBC solo para Flyway
quarkus.datasource.jdbc.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:reservas_db}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver

# Hibernate Reactive
quarkus.hibernate-orm.database.generation=none

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

# OpenAPI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Reservas Service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Sistema de reservas de profesionales

# Logs
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
quarkus.console.color=false

# Fault Tolerance
quarkus.smallrye-fault-tolerance.mp-compatibility=false
quarkus.hibernate-orm.query.in-clause-parameter-padding=true